version: '3.8'

services:
  thronebound_bot:
    build: .
    container_name: thronebound_bot
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    environment:
      - CHROMA_HOST=127.0.0.1
    volumes:
      - .:/app
      - thronebound_db_data:/app/data

  chromadb:
    image: chromadb/chroma:latest
    container_name: thronebound_chromadb
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

volumes:
  chroma_data:
  thronebound_db_data:
