import random

import datetime
import math
import json

from database.models import Kingdom, Sovereign, Character, Tile, ActionQueue
from ai.engine import validate_legal_heir

async def handle_succession(channel, bot, kingdom_id: int):
    """
    Handles the death of a Sovereign. Validates the designated heir against the legal heir.
    Applies regency penalties if the heir is under 16.
    """
    with bot.SessionLocal() as db:
        kingdom = db.get(Kingdom, kingdom_id)
        if not kingdom or not kingdom.is_active:
            return

        latest_sov = db.query(Sovereign).filter_by(kingdom_id=kingdom.id).order_by(Sovereign.id.desc()).first()
        if not latest_sov or latest_sov.is_alive:
            return

        if not latest_sov.designated_heir_id:
            kingdom.is_active = False
            db.commit()
            if channel:
                await channel.send("💀 **Seu soberano morreu sem deixar herdeiros! O reino caiu em ruínas. Game Over.**")
            return

        # AI Legal Validation
        family_members = db.query(Character).filter(
            Character.kingdom_id == kingdom.id,
            Character.is_alive == True,
            Character.relacao_familiar != "Nenhum"
        ).all()

        legal_heir_name = await validate_legal_heir(family_members, kingdom.lei_sucessao, kingdom.lei_genero)
        designated_heir = db.get(Character, latest_sov.designated_heir_id)

        if not designated_heir:
            kingdom.is_active = False
            db.commit()
            if channel:
                await channel.send("💀 **Seu soberano morreu e seu herdeiro designado não pôde ser encontrado! O reino caiu em ruínas. Game Over.**")
            return

        # Compare designated heir with legal heir
        if designated_heir.nome.lower() == legal_heir_name.lower():

            # Check for Regency
            regency_msg = ""
            if designated_heir.idade < 16:
                kingdom.estabilidade = max(0, kingdom.estabilidade - 15)
                regency_msg = f"\n⚠️ **Regência Declarada:** Como {designated_heir.nome} tem apenas {designated_heir.idade} anos, um conselho de regência governará em seu nome. A estabilidade caiu drasticamente (-15)."

            if channel:
                await channel.send(f"👑 **O rei está morto! A sucessão ocorreu de forma pacífica e legal. Longa vida ao rei! O herdeiro {designated_heir.nome} assume o trono.**{regency_msg}")

            new_sov = Sovereign(
                kingdom_id=kingdom.id,
                name=designated_heir.nome,
                age=designated_heir.idade
            )
            db.add(new_sov)
            db.commit()
        else:
            # Usurpation / Civil War -> Game Over
            kingdom.is_active = False
            db.commit()
            if channel:
                await channel.send(f"🔥 **GUERRA CIVIL!** O Soberano morreu e tentou passar o trono para {designated_heir.nome}, mas a lei exigia que o trono fosse para **{legal_heir_name}**. O reino se despedaçou em chamas e sangue pela usurpação. **Game Over.**")

async def roll_universal_aging_and_death(db, kingdom_id: int, channel):
    """
    To be called whenever a cycle completes. Ages all characters and the Sovereign,
    and rolls death chances for anyone >= 75.
    Announces council vacancies if a councilor dies.
    """
    kingdom = db.get(Kingdom, kingdom_id)
    if not kingdom:
        return

    # 1. Age the Sovereign separately since they are in their own table
    sov = db.query(Sovereign).filter_by(kingdom_id=kingdom.id, is_alive=True).first()
    if sov:
        sov.age_up()
        sov.roll_natural_death()

    # 2. Age all living Characters (Council and Family)
    all_characters = db.query(Character).filter_by(kingdom_id=kingdom.id, is_alive=True).all()

    for char in all_characters:
        char.age_up()

        # Determine if character died naturally this cycle
        if char.roll_natural_death():
            # Check if this character is the active Sovereign (in case they are mapped)
            if sov and sov.is_alive and sov.name == char.nome:
                sov.is_alive = False

            # Announce Council death
            if char.cargo_conselho != "Nenhum":
                if channel:
                    await channel.send(f"🕯️ **Luto Oficial:** O {char.cargo_conselho} **{char.nome}** faleceu de causas naturais aos {char.idade} anos. O cargo agora está vago.")
                char.cargo_conselho = "Nenhum"

    db.commit()

def apply_db_updates(db, kingdom_id: int, db_updates: dict, char_updates: list) -> bool:
    """
    Applies the resource, stability, and character state changes generated by the AI Engine.
    Returns True if the sovereign died as a result.
    """
    kingdom = db.get(Kingdom, kingdom_id)
    if not kingdom:
        return False

    sov = db.query(Sovereign).filter_by(kingdom_id=kingdom.id, is_alive=True).first()

    kingdom.gold = max(0, kingdom.gold + db_updates.get("ouro", 0))
    kingdom.army = max(0, kingdom.army + db_updates.get("exercito", 0))
    kingdom.influence = max(0, kingdom.influence + db_updates.get("influencia", 0))
    kingdom.estabilidade = max(0, min(100, kingdom.estabilidade + db_updates.get("estabilidade", 0)))

    sovereign_died = False
    if db_updates.get("soberano_morto", False) and sov:
        sov.is_alive = False
        sovereign_died = True

    for cu in char_updates:
        char_id = cu.get("id")
        if char_id:
            c = db.get(Character, char_id)
            if c and c.kingdom_id == kingdom.id:
                c.evaluate_loyalty_shift(cu.get("lealdade", 0))
                c.evaluate_power_shift(cu.get("poder", 0))
                if cu.get("is_alive") is False:
                    c.is_alive = False

    db.commit()
    return sovereign_died

def enqueue_delayed_action(db, kingdom_id: int, action_text: str, reino_destino: str, dist_estimada: float,
                           ciclo_completo: bool, master_narrative: str = None, master_resolution: dict = None) -> float:
    """
    Calculates distance delay and queues an action.
    If the action was manually reviewed by the Master, packages the final narrative and db_updates
    into the enqueued text so the background loop can simply print/apply it when it arrives.
    Returns the delay in hours.
    """
    kingdom = db.get(Kingdom, kingdom_id)
    dist_real = float(dist_estimada)

    if reino_destino:
        target_k = db.query(Kingdom).filter(Kingdom.name.ilike(f"%{reino_destino}%"), Kingdom.is_active==True).first()
        if target_k:
            k1_cap = db.query(Tile).filter_by(kingdom_id=kingdom.id).first()
            k2_cap = db.query(Tile).filter_by(kingdom_id=target_k.id).first()
            if k1_cap and k2_cap:
                dist_real = math.sqrt((k2_cap.x - k1_cap.x)**2 + (k2_cap.y - k1_cap.y)**2)

    delay_in_hours = (dist_real / 100.0) * 24
    resolve_time = datetime.datetime.utcnow() + datetime.timedelta(hours=delay_in_hours)

    enqueued_text = action_text

    # If the master resolved it, pack the JSON so it can be un-packed and applied upon arrival
    if master_narrative and master_resolution:
        enqueued_text += f"\n\n[RESOLUÇÃO DO MESTRE JÁ PRONTA]:\n{master_narrative}\n[DB_UPDATES_PENDING]:\n{json.dumps(master_resolution)}"

    if ciclo_completo:
        enqueued_text += " [SYSTEM: Este evento completa um Ciclo]"

    new_action = ActionQueue(
        kingdom_id=kingdom.id,
        action_text=enqueued_text,
        resolve_at=resolve_time,
        status="pending"
    )
    db.add(new_action)
    db.commit()

    return delay_in_hours
